; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32cam

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_src_filter = -<*> +<examples/Esp32-cam-RC-Car/>
build_flags = 
    -D BOARD_HAS_PSRAM
